# Generated by Django 5.1 on 2024-09-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('curso', models.CharField(choices=[('alimentos', 'Alimentos'), ('apicultura', 'Apicultura'), ('informatica', 'Informática')], max_length=11)),
                ('img', models.ImageField(upload_to='imagem/')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.cidade')),
            ],
        ),
    ]
